# 小程序自动化部署

name: auto_deploy

on:
  push:
    branches: [dev,uat,master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置变量
        env:
          message: ${{ github.event.commits[0].message }}
          branch: ${{ steps }}
          branch2: ${{ github.ref }}
        run: |
          echo $message
          echo $branch2
          echo $branch
 
