# 小程序自动化部署

name: auto_deploy

on:
  push:
    branches: [dev,uat,master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 选择 node 版本
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 下载依赖
        run: npm install

      - name: 运行构建脚本
        run: npm run build:dev-weixin

      - name: 部署
        run: node ci.js $PROJECT_VERSION.$CI_COMMIT_SHORT_SHA.alpha 1 $(git log -1 --pretty=%B)




# 安装依赖&&构建打包
#build dev:
#  stage: build
#  only:
#    - dev
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build:dev-weixin
#    - node ci.js $PROJECT_VERSION.$CI_COMMIT_SHORT_SHA.alpha 1 $(git log -1 --pretty=%B)
#
#build preview:
#  stage: build
#  only:
#    - uat
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build:uat-weixin
#    - node ci.js $PROJECT_VERSION.beta 2 $(git log -1 --pretty=%B)
#
#build prd:
#  stage: build
#  only:
#    - master
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build
#    - node ci.js $PROJECT_VERSION 3 $(git log -1 --pretty=%B)
