# 小程序自动化部署

name: auto_deploy

on:
  # 代码推送时
  push:
    branches: [ dev, uat, master, main ]

  # 创建tag时
#  release:
#    types: [ created ]


jobs:
  build:
    if: "contains(github.event.head_commit.message, '发布')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        - name: 小程序自动化部署
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            cache: 'npm'

        - run: npm install
        - run: npm run build:dev-weixin
        - run: node ci.js --desc=${{ github.event.head_commit.message }} --robot=${{ github.ref_name }}

