# 小程序自动化部署

name: auto_deploy

on:
  push:
    branches: [dev,uat,master]

jobs:
  build:
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'


      - run: npm install
      - run: npm run build:dev-weixin
      - run: node ci.js




# 安装依赖&&构建打包
#build dev:
#  stage: build
#  only:
#    - dev
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build:dev-weixin
#    - node ci.js $PROJECT_VERSION.$CI_COMMIT_SHORT_SHA.alpha 1 $(git log -1 --pretty=%B)
#
#build preview:
#  stage: build
#  only:
#    - uat
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build:uat-weixin
#    - node ci.js $PROJECT_VERSION.beta 2 $(git log -1 --pretty=%B)
#
#build prd:
#  stage: build
#  only:
#    - master
#  tags:
#    - f2e
#  script:
#    - cnpm i
#    - npm run build
#    - node ci.js $PROJECT_VERSION 3 $(git log -1 --pretty=%B)
