# 小程序自动化部署

name: auto_deploy

on:
  # 代码推送时
  push:
    branches: [ dev, uat, master, main ]

  # 创建tag时
#  release:
#    types: [ created ]


jobs:
  build:
#     if: "contains(github.event.head_commit.message, '发布')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 node 版本为 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: 小程序自动化部署
        env:
          message: ${{ github.event.head_commit.message }}
          branch: ${{ github.ref_name }}
        run: |
            npm install
            npm run build:dev-weixin
            node ci.js --desc=$message --robot=$branch
          
