# 小程序自动化部署

name: auto_deploy

on:
  push:
    branches: [dev,uat,master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 获取当前分支
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
          BRANCH: ${{ STEPS_CONTEXT.extract_branch.outputs.branch }}
        run: echo "$BRANCH"

      - name: 获取提交信息
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          COMMIT: ${{ GITHUB_CONTEXT.event.commits[0].message }}
        run: echo "$COMMIT"
 
